import Telegraph from 'telegra.ph';
import { Node, Page } from 'telegra.ph/typings/telegraph';
import { TELEGRAPH_AUTHOR_NAME, TELEGRAPH_AUTHOR_URL, TELEGRAPH_TOKEN } from '../config/constants';

export default async function createTelegraph(title: string, pictureUrls: string[], originalLink: string): Promise<Page> {
  const client = new Telegraph(TELEGRAPH_TOKEN);
  const context: Node[] = [];
  pictureUrls.forEach((url: string) => {
    context.push({ tag: 'figure', children: [{ tag: 'img', attrs: { src: url } }] });
  });
  context.push({
    tag: 'p',
    children: [`Generated By `, { tag: 'a', attrs: { href: `https://github.com/cmd2001/KiChan` }, children: ['KiChan'] }]
  });
  context.push({ tag: 'p', children: [`Original Link: `, { tag: 'a', attrs: { href: originalLink }, children: [originalLink] }] });
  return client.createPage(title, context, TELEGRAPH_AUTHOR_NAME, TELEGRAPH_AUTHOR_URL, false);
}
